"""Slack notifier for LineagePulse.

Posts a per-incident, per-owner message to a configured incoming webhook
URL. In ``DRY_RUN`` mode it logs the payload instead of sending.
"""

from __future__ import annotations

import json
import logging
from typing import Any

import requests

from lineagepulse.config import Settings
from lineagepulse.models import Incident, IncidentReport

logger = logging.getLogger(__name__)


def post_incident(
    incident: Incident,
    report: IncidentReport,
    settings: Settings,
) -> str | None:
    """Send the incident to Slack. Returns the message timestamp on success."""
    payload = render_blocks(incident, report, settings)
    channel = _route_channel(incident, settings)

    if settings.dry_run:
        logger.info("[DRY_RUN] would post to %s:\n%s", channel, json.dumps(payload, indent=2))
        return f"dry-run-{incident.id}"

    if not settings.slack_webhook_url:
        logger.warning("SLACK_WEBHOOK_URL not configured — skipping notification")
        return None

    try:
        r = requests.post(
            settings.slack_webhook_url,
            json={"channel": channel, **payload},
            timeout=10,
        )
        r.raise_for_status()
        ts = r.json().get("ts") if r.headers.get("content-type", "").startswith("application/json") else None
        return ts
    except Exception as exc:  # noqa: BLE001
        logger.warning("Slack post failed: %s", exc)
        return None


# ----------------------------------------------------------------- rendering
def render_blocks(incident: Incident, report: IncidentReport, settings: Settings) -> dict[str, Any]:
    severity_emoji = {
        "low": ":white_check_mark:",
        "medium": ":warning:",
        "high": ":rotating_light:",
        "critical": ":fire:",
    }.get(incident.severity.value, ":grey_question:")

    fields: list[dict[str, Any]] = [
        {"type": "mrkdwn", "text": f"*Severity*\n{severity_emoji} {incident.severity.value.upper()}"},
        {"type": "mrkdwn", "text": f"*Asset*\n`{incident.asset.name or incident.asset.urn}`"},
        {"type": "mrkdwn", "text": f"*Detected*\n{incident.detected_at.strftime('%Y-%m-%d %H:%M UTC')}"},
        {"type": "mrkdwn", "text": f"*Owners*\n{', '.join(incident.asset.owners) or '_(none on file)_'}"},
    ]

    blast = incident.blast_radius
    if blast and blast.total_impacted:
        blast_line = (
            f"{len(blast.downstream)} downstream, "
            f"{len(blast.affected_ml_models)} ML model(s), "
            f"{len(blast.affected_dashboards)} dashboard(s)"
        )
        fields.append({"type": "mrkdwn", "text": f"*Blast radius*\n{blast_line}"})

    blocks: list[dict[str, Any]] = [
        {
            "type": "header",
            "text": {"type": "plain_text", "text": f"{severity_emoji} {incident.title}"},
        },
        {
            "type": "section",
            "text": {"type": "mrkdwn", "text": f"*Summary*\n{report.executive_summary}"},
        },
        {"type": "section", "fields": fields},
        {
            "type": "section",
            "text": {"type": "mrkdwn", "text": f"*Root cause hypothesis*\n{report.root_cause_hypothesis}"},
        },
        {
            "type": "section",
            "text": {"type": "mrkdwn", "text": f"*Suggested fix*\n{report.suggested_fix}"},
        },
    ]

    if report.recommended_actions:
        actions_text = "\n".join(f"• {a}" for a in report.recommended_actions)
        blocks.append(
            {
                "type": "section",
                "text": {"type": "mrkdwn", "text": f"*Recommended actions*\n{actions_text}"},
            }
        )

    if incident.datahub_document_urn:
        blocks.append(
            {
                "type": "context",
                "elements": [
                    {
                        "type": "mrkdwn",
                        "text": f":pencil: Incident written back to DataHub: `{incident.datahub_document_urn}`",
                    }
                ],
            }
        )

    blocks.append(
        {
            "type": "context",
            "elements": [
                {
                    "type": "mrkdwn",
                    "text": "Generated by <https://github.com/ademidun/lineagepulse|LineagePulse> — "
                            "DataHub Agent Hackathon submission",
                }
            ],
        }
    )

    return {"blocks": blocks, "text": f"{incident.severity.value.upper()}: {incident.title}"}


def _route_channel(incident: Incident, settings: Settings) -> str:
    if incident.asset.domain and incident.asset.domain in settings.slack_channel_routing:
        return settings.slack_channel_routing[incident.asset.domain]
    return settings.slack_default_channel
